### PR TITLE
Setup project

### PR DESCRIPTION
**Pull request by wuletawwonte**
Changes in this PR
- Create empty react app by running `npx create-react-app .` in the terminal
- Install `SASS` package in the project
- Install `react-router-dom` package in the project
- Create global variables sass file and add breakpoint mixins in it
- Create global index sass file to hold global stylings for elements
- Add linter configuration files 
- Add routes file to hold all the routes of the application

### CODE REVIEW

**Review by ismailakinkunmi — CHANGES_REQUESTED** [review]
## STATUS: CHANGES REQUIRED
Hi @wuletawwonte,
Good job so far!
### Project highlights:
- [x] All linter checks are passing
- [x] Descriptive commit messages

### Required Changes

- [ ] Please I would suggest you change the page folder to components
- [ ] Please install redux on react app to manage this application state as required for the project requirement.

Cheers and Happy coding!
You can reach me on slack or zoom in case of any doubt

**Comment by wuletawwonte** [comment]
## Hi @ismailakinkunmi 
- I think creating a separate folder for pages and components is a better approach. That is what I thought when creating the pages folder. I have also created a components folder for the components of the app now.

**Comment by ismailakinkunmi** [comment]
@wuletawwonte Please come on zoom waiting for you

**Review by ismailakinkunmi — CHANGES_REQUESTED** [review]
### Status Changes Required
Hi @wuletawwonte,

After I updated the PR with git pull I noticed you have added navbar and components folder including Redux showing in package.json file but there is no redux file or folder in the project directory nor in the src folder to work with, Please fix it by creating store.js file inside src folder and import createStore from redux.

## Required Changes
- [ ]  add the redux file or folder to the project directory or src folder

**Comment by wuletawwonte** [comment]
## Hi @ismailakinkunmi 
- Sorry I was out for lunch. I left that part for later. When we start working on the application's state, we can create it. Is it required right now for those files to be created? The API is not even created yet.

**Review by ismailakinkunmi — APPROVED** [review]
## Status: Approved
Hi @wuletawwonte,
Congratulation, Project is complete nothing else to say other than it is time to merge it.
cheer and happy coding

**Pull request merged**
